name: eai-eval
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=hda65f42_8
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - cmake=4.1.2=hc85cc9f_0
  - icu=75.1=he02047a_0
  - keyutils=1.6.3=hb9d3cd8_0
  - krb5=1.21.3=h659f571_0
  - ld_impl_linux-64=2.44=h1aa0949_5
  - libcurl=8.17.0=h4e3cde8_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.1=hecca717_0
  - libffi=3.5.2=h9ec8514_0
  - libgcc=15.2.0=h767d61c_7
  - libgcc-ng=15.2.0=h69a702a_7
  - libgomp=15.2.0=h767d61c_7
  - liblzma=5.8.1=hb9d3cd8_2
  - liblzma-devel=5.8.1=hb9d3cd8_2
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libsqlite=3.51.0=hee844dc_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.2.0=h8f9b012_7
  - libstdcxx-ng=15.2.0=h4852527_7
  - libuuid=2.41.2=he9a06e4_0
  - libuv=1.51.0=hb03c661_1
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.6.0=h26f9b46_0
  - python=3.8.20=h4a871b0_2_cpython
  - readline=8.2=h8c095d6_2
  - rhash=1.4.6=hb9d3cd8_1
  - setuptools=75.3.0=pyhd8ed1ab_0
  - tk=8.6.13=noxft_hd72426e_102
  - wheel=0.45.1=pyhd8ed1ab_0
  - xz=5.8.1=hbcc6ac9_2
  - xz-gpl-tools=5.8.1=hbcc6ac9_2
  - xz-tools=5.8.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aenum==3.1.16
      - asttokens==3.0.0
      - attrs==25.3.0
      - backcall==0.2.0
      - bddl-eval==1.0.1
      - beautifulsoup4==4.14.2
      - certifi==2025.11.12
      - charset-normalizer==3.4.4
      - cloudpickle==3.1.2
      - contourpy==1.1.1
      - cycler==0.12.1
      - decorator==5.2.1
      - eai==0.1
      - exceptiongroup==1.3.0
      - executing==2.2.1
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.2
      - filelock==3.16.1
      - fire==0.7.1
      - fonttools==4.57.0
      - freetype-py==2.5.1
      - future==1.0.0
      - gdown==5.2.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - gputil==1.4.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - gymnasium==1.1.1
      - h5py==3.11.0
      - idna==3.11
      - igibson==2.2.3
      - imageio==2.35.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.1.0
      - ipdb==0.13.13
      - ipython==8.12.3
      - jedi==0.19.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-core==5.8.1
      - jupytext==1.17.1
      - kiwisolver==1.4.7
      - lark==1.3.1
      - lazy-loader==0.4
      - markdown-it-py==3.0.0
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mdit-py-plugins==0.4.2
      - mdurl==0.1.2
      - nbformat==5.10.4
      - networkx==3.1
      - numpy==1.24.4
      - opencv-python==4.12.0.88
      - packaging==25.0
      - pandas==2.0.3
      - parso==0.8.5
      - pddlgym==0.0.7
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==9.5.0
      - pip==25.0.1
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - progressbar==2.5
      - prompt-toolkit==3.0.52
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py360convert==0.1.0
      - pyarrow==17.0.0
      - pybullet-svl==3.1.6.4
      - pygments==2.19.2
      - pyparsing==3.1.4
      - pyquaternion==0.9.9
      - pysocks==1.7.1
      - pytest==8.3.5
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - pywavelets==1.4.1
      - pyyaml==6.0
      - referencing==0.35.1
      - requests==2.32.4
      - rpds-py==0.20.1
      - scikit-image==0.21.0
      - scipy==1.10.1
      - six==1.17.0
      - smmap==5.0.2
      - soupsieve==2.7
      - stack-data==0.6.3
      - termcolor==2.4.0
      - tifffile==2023.7.10
      - tomli==2.3.0
      - torch==1.13.1+cpu
      - torchaudio==0.13.1+cpu
      - torchvision==0.14.1+cpu
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transforms3d==0.4.2
      - trimesh==4.9.0
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - urllib3==2.2.3
      - wcwidth==0.2.14
      - zipp==3.20.2
prefix: /home/yeah/anaconda3/envs/eai-eval
